version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: organizatea_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: organizatea_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: organizatea_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: organizatea
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: